services:
  - type: web
    name: eating-pandas
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
