apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ha-cloud-webapp
  namespace: ha-webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ha-cloud-webapp
  minReplicas: 4
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
